# Generated by Django 3.0.5 on 2020-04-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_jwt_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
