# Generated by Django 3.0.5 on 2020-04-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_jwt_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_last_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
